name: wallpaper
description: Simple wallpaper flutter

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.5
  flutter_staggered_grid_view: ^0.3.0
  image_picker: ^0.6.5+2
  path_provider: ^1.6.7
  permission_handler: ^5.0.0+hotfix.4
  sqflite: ^1.3.0
  firebase_storage: ^3.1.5
  uuid: ^2.0.4
  rxdart: ^0.24.0
  intl: ^0.16.1
  http: ^0.12.0+4
  cached_network_image: ^2.1.0+1
  tuple: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0


flutter:
  uses-material-design: true
  assets:
    - assets/picture.png
    - assets/drawer_header_image.jpg
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/NunitoSans-Regular.ttf
